---
title: "RNA-seq Mouse Placenta"
author: "Ha T. H. Vu"
output: html_document
---
  
```{r setup, include=FALSE}
options(max.print = "75")
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "Files/",
  fig.width = 8,
  prompt = FALSE,
  tidy = FALSE,
  message = FALSE,
  warning = TRUE
)
knitr::opts_knit$set(width = 75)
```

Documentation for the analysis of mouse placental RNA-seq data at e7.5, e8.5 and e9.5.

```{r, eval=F}
library("clusterProfiler")
library("org.Mm.eg.db")

go <- function(subnetworkGenes) {
  GO <- enrichGO(gene = subnetworkGenes, OrgDb=org.Mm.eg.db, ont = "BP", pvalueCutoff = 1, qvalueCutoff = 1, maxGSSize=1000, readable = T, keyType = "ENSEMBL")
  res <- as.data.frame(GO@result)
  res$Rank <- seq(1, nrow(res))
  res$GeneRatio <- sapply(strsplit(res$GeneRatio, "/"), function(x) as.numeric(x[1])/as.numeric(x[2]))
  res$BgRatio <- sapply(strsplit(res$BgRatio, "/"), function(x) as.numeric(x[1])/as.numeric(x[2]))
  res$Fold <- as.numeric(res$GeneRatio)/as.numeric(res$BgRatio)
  res <- res[res$qvalue <= 0.05 & res$Fold >= 2 & res$Count >= 5,]
  
  return(res)
}
```
Similar to STRING network analysis, we carry out GO analysis first to evaluate the biological relevant of the networks. We can use the same function `go()`.
```{r, eval=F}
library(dplyr)
t2g <- read.table("Files/t2g.txt", header = T)
terms <- c("inflammatory response", "female pregnancy", "morphogenesis of a branching structure",
           "lipid biosynthetic process", "endothelial cell proliferation", "cholesterol metabolic process",
           "response to insulin", "vasculature development", "positive regulation of cell migration", "epithelium migration",
	   "placenta development", "tube morphogenesis", "regulation of cell migration")

for (time in c("e7.5", "e8.5", "e9.5")) {
  for (i in 1:3) {
      #geneList <- read.table(paste0("Files/GENIE3/", time, "/v2pronto/", time, "_", i, "_nodeTable.csv"), header = T, sep = ",")
      #genes <- inner_join(geneList, distinct(t2g[,2:3]), by = c("name" = "ext_gene"))
      #goTerms <- go(genes$ens_gene)
      #save(goTerms, file = paste0("Files/GENIE3/", time, "/v2pronto/", time, "_", i, "_BP_filtered.rda"))
      load(paste0("Files/GENIE3/", time, "/v2pronto/", time, "_", i, "_BP_filtered.rda"))
      print(paste0("Files/GENIE3/", time, "/v2pronto/", time, "_", i, "_BP_filtered.rda"))
      print(goTerms[goTerms$Description %in% terms, c("Description", "qvalue", "Count", "Rank", "Fold")])
  }
}
```

